2018-11-16 21:50:44 ERROR (SyncWorker_0) [homeassistant.util.yaml] YAML file /home/homeassistant/.homeassistant/automations.yaml contains duplicate key "trigger". Check lines 23 and 27.
2018-11-16 21:50:46 DEBUG (SyncWorker_9) [mysensors.persistence] Loading sensors from persistence file /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:50:46 ERROR (SyncWorker_6) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Invalid values: {16: '0'}: switch platform: node 2 child 3: S_DOOR requires value_type V_ARMED @ data[15]
2018-11-16 21:50:46 INFO (MainThread) [homeassistant.components.mysensors] Adding new devices: [<Entity Water Sensor 2 3: off>]
2018-11-16 21:50:46 INFO (MainThread) [homeassistant.components.mysensors] Adding new devices: [<Entity guesthouse-climate 9 0: None>, <Entity guesthouse-climate 9 1: None>]
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: Water Sensor 2 3: value_type 16, value = 0
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: guesthouse-climate 9 1: value_type 0, value = 24.5
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.device] Entity update: guesthouse-climate 9 0: value_type 1, value = 36.7
2018-11-16 21:50:46 INFO (MainThread) [mysensors.gateway_tcp] Trying to connect to ('192.168.0.177', 5003)
2018-11-16 21:50:46 INFO (MainThread) [mysensors] Connected to <_SelectorSocketTransport fd=16 read=idle write=<idle, bufsize=0>>
2018-11-16 21:50:46 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;14;Gateway startup complete.
2018-11-16 21:50:46 INFO (MainThread) [mysensors.handler] n:0 c:255 t:3 s:14 p:Gateway startup complete.
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Node update: node 0 child 255
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Not a child update for node 0
2018-11-16 21:50:46 DEBUG (MainThread) [mysensors] Receiving 0;255;0;0;18;2.2.0
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Node update: node 0 child 255
2018-11-16 21:50:46 DEBUG (MainThread) [homeassistant.components.mysensors.gateway] Not a child update for node 0
2018-11-16 21:50:50 ERROR (SyncWorker_4) [homeassistant.util.json] Saving JSON file failed: /home/homeassistant/.homeassistant/.storage/core.config_entries
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/json.py", line 55, in save_json
    dir=tmp_path, delete=False) as fdesc:
  File "/usr/lib/python3.6/tempfile.py", line 688, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmpt2ydgaq1'
2018-11-16 21:50:50 ERROR (MainThread) [homeassistant.helpers.storage] Error writing config for core.config_entries: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmpt2ydgaq1'
2018-11-16 21:50:56 ERROR (SyncWorker_6) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:50:56 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:50:56 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:50:57 ERROR (SyncWorker_3) [homeassistant.util.json] Saving JSON file failed: /home/homeassistant/.homeassistant/.storage/core.device_registry
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/json.py", line 55, in save_json
    dir=tmp_path, delete=False) as fdesc:
  File "/usr/lib/python3.6/tempfile.py", line 688, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmpiw_ugh1v'
2018-11-16 21:50:57 ERROR (MainThread) [homeassistant.helpers.storage] Error writing config for core.device_registry: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmpiw_ugh1v'
2018-11-16 21:50:58 ERROR (SyncWorker_7) [homeassistant.util.json] Saving JSON file failed: /home/homeassistant/.homeassistant/.storage/core.entity_registry
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/json.py", line 55, in save_json
    dir=tmp_path, delete=False) as fdesc:
  File "/usr/lib/python3.6/tempfile.py", line 688, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmp8on5en_e'
2018-11-16 21:50:58 ERROR (MainThread) [homeassistant.helpers.storage] Error writing config for core.entity_registry: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmp8on5en_e'
2018-11-16 21:51:06 ERROR (SyncWorker_4) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:51:06 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:51:06 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:51:07 ERROR (SyncWorker_7) [homeassistant.util.json] Could not parse JSON content: /home/homeassistant/.homeassistant/plex.conf
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/json.py", line 30, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-11-16 21:51:07 ERROR (MainThread) [homeassistant.setup] Error during setup of component octoprint
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/octoprint.py", line 95, in setup
    for printer in config[DOMAIN]:
KeyError: 'octoprint'
2018-11-16 21:51:07 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform plex
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/json.py", line 30, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/plex.py", line 61, in setup_platform
    file_config = load_json(hass.config.path(PLEX_CONFIG_FILE))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/json.py", line 36, in load_json
    raise HomeAssistantError(error)
homeassistant.exceptions.HomeAssistantError: Expecting value: line 1 column 1 (char 0)
2018-11-16 21:51:16 ERROR (SyncWorker_1) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:51:16 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:51:17 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:51:18 ERROR (SyncWorker_7) [homeassistant.util.json] Saving JSON file failed: /home/homeassistant/.homeassistant/.storage/core.entity_registry
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/json.py", line 55, in save_json
    dir=tmp_path, delete=False) as fdesc:
  File "/usr/lib/python3.6/tempfile.py", line 688, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmplixxrdob'
2018-11-16 21:51:18 ERROR (MainThread) [homeassistant.helpers.storage] Error writing config for core.entity_registry: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/.storage/tmplixxrdob'
2018-11-16 21:51:26 ERROR (SyncWorker_0) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:51:27 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:51:27 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:51:36 ERROR (SyncWorker_0) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:51:37 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:51:37 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:51:46 ERROR (SyncWorker_0) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:51:47 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:51:47 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:51:56 ERROR (SyncWorker_0) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:51:57 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:51:57 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:52:06 ERROR (SyncWorker_0) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:52:07 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:52:07 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:52:16 ERROR (SyncWorker_8) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:52:17 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:52:17 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:52:26 ERROR (SyncWorker_3) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:52:27 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:52:27 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:52:36 ERROR (SyncWorker_7) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:52:37 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:52:37 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:52:46 ERROR (SyncWorker_0) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:52:47 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:52:47 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:52:56 ERROR (SyncWorker_6) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:52:57 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:52:58 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
2018-11-16 21:53:06 ERROR (SyncWorker_9) [mysensors.persistence] Permission denied when writing to /home/homeassistant/.homeassistant/mysensors1.json
2018-11-16 21:53:08 DEBUG (MainThread) [mysensors] Sending 0;255;3;0;2;
2018-11-16 21:53:08 DEBUG (MainThread) [mysensors] Receiving 0;255;3;0;2;2.2.0
